local M = {}

---@class Verse
---@field book string
---@field chapter string
---@field verse_number string
---@field verse_prefix_newline boolean
---@field verse string
---@field verse_suffix_newline boolean

---@type table<string, { chapter: integer, max_verse: integer }[]>
local bible_data = {
  ["1chronicles"] = {
    { chapter = 1,  max_verse = 54 },
    { chapter = 2,  max_verse = 55 },
    { chapter = 3,  max_verse = 24 },
    { chapter = 4,  max_verse = 43 },
    { chapter = 5,  max_verse = 26 },
    { chapter = 6,  max_verse = 81 },
    { chapter = 7,  max_verse = 40 },
    { chapter = 8,  max_verse = 40 },
    { chapter = 9,  max_verse = 44 },
    { chapter = 10, max_verse = 14 },
    { chapter = 11, max_verse = 47 },
    { chapter = 12, max_verse = 40 },
    { chapter = 13, max_verse = 14 },
    { chapter = 14, max_verse = 17 },
    { chapter = 15, max_verse = 29 },
    { chapter = 16, max_verse = 43 },
    { chapter = 17, max_verse = 27 },
    { chapter = 18, max_verse = 17 },
    { chapter = 19, max_verse = 19 },
    { chapter = 20, max_verse = 8 },
    { chapter = 21, max_verse = 30 },
    { chapter = 22, max_verse = 19 },
    { chapter = 23, max_verse = 32 },
    { chapter = 24, max_verse = 31 },
    { chapter = 25, max_verse = 31 },
    { chapter = 26, max_verse = 32 },
    { chapter = 27, max_verse = 34 },
    { chapter = 28, max_verse = 21 },
    { chapter = 29, max_verse = 30 },
  },
  ["1corinthians"] = {
    { chapter = 1,  max_verse = 31 },
    { chapter = 2,  max_verse = 16 },
    { chapter = 3,  max_verse = 23 },
    { chapter = 4,  max_verse = 21 },
    { chapter = 5,  max_verse = 13 },
    { chapter = 6,  max_verse = 20 },
    { chapter = 7,  max_verse = 40 },
    { chapter = 8,  max_verse = 13 },
    { chapter = 9,  max_verse = 27 },
    { chapter = 10, max_verse = 33 },
    { chapter = 11, max_verse = 34 },
    { chapter = 12, max_verse = 31 },
    { chapter = 13, max_verse = 13 },
    { chapter = 14, max_verse = 40 },
    { chapter = 15, max_verse = 58 },
    { chapter = 16, max_verse = 24 },
  },
  ["1john"] = {
    { chapter = 1, max_verse = 10 },
    { chapter = 2, max_verse = 29 },
    { chapter = 3, max_verse = 24 },
    { chapter = 4, max_verse = 21 },
    { chapter = 5, max_verse = 21 },
  },
  ["1kings"] = {
    { chapter = 1,  max_verse = 53 },
    { chapter = 2,  max_verse = 46 },
    { chapter = 3,  max_verse = 28 },
    { chapter = 4,  max_verse = 34 },
    { chapter = 5,  max_verse = 18 },
    { chapter = 6,  max_verse = 38 },
    { chapter = 7,  max_verse = 51 },
    { chapter = 8,  max_verse = 66 },
    { chapter = 9,  max_verse = 28 },
    { chapter = 10, max_verse = 29 },
    { chapter = 11, max_verse = 43 },
    { chapter = 12, max_verse = 33 },
    { chapter = 13, max_verse = 34 },
    { chapter = 14, max_verse = 31 },
    { chapter = 15, max_verse = 34 },
    { chapter = 16, max_verse = 34 },
    { chapter = 17, max_verse = 24 },
    { chapter = 18, max_verse = 46 },
    { chapter = 19, max_verse = 21 },
    { chapter = 20, max_verse = 43 },
    { chapter = 21, max_verse = 29 },
    { chapter = 22, max_verse = 53 },
  },
  ["1peter"] = {
    { chapter = 1, max_verse = 25 },
    { chapter = 2, max_verse = 25 },
    { chapter = 3, max_verse = 22 },
    { chapter = 4, max_verse = 19 },
    { chapter = 5, max_verse = 14 },
  },
  ["1samuel"] = {
    { chapter = 1,  max_verse = 28 },
    { chapter = 2,  max_verse = 36 },
    { chapter = 3,  max_verse = 21 },
    { chapter = 4,  max_verse = 22 },
    { chapter = 5,  max_verse = 12 },
    { chapter = 6,  max_verse = 21 },
    { chapter = 7,  max_verse = 17 },
    { chapter = 8,  max_verse = 22 },
    { chapter = 9,  max_verse = 27 },
    { chapter = 10, max_verse = 27 },
    { chapter = 11, max_verse = 15 },
    { chapter = 12, max_verse = 25 },
    { chapter = 13, max_verse = 23 },
    { chapter = 14, max_verse = 52 },
    { chapter = 15, max_verse = 35 },
    { chapter = 16, max_verse = 23 },
    { chapter = 17, max_verse = 58 },
    { chapter = 18, max_verse = 30 },
    { chapter = 19, max_verse = 24 },
    { chapter = 20, max_verse = 42 },
    { chapter = 21, max_verse = 15 },
    { chapter = 22, max_verse = 23 },
    { chapter = 23, max_verse = 29 },
    { chapter = 24, max_verse = 22 },
    { chapter = 25, max_verse = 44 },
    { chapter = 26, max_verse = 25 },
    { chapter = 27, max_verse = 12 },
    { chapter = 28, max_verse = 25 },
    { chapter = 29, max_verse = 11 },
    { chapter = 30, max_verse = 31 },
    { chapter = 31, max_verse = 13 },
  },
  ["1thessalonians"] = {
    { chapter = 1, max_verse = 10 },
    { chapter = 2, max_verse = 20 },
    { chapter = 3, max_verse = 13 },
    { chapter = 4, max_verse = 18 },
    { chapter = 5, max_verse = 28 },
  },
  ["1timothy"] = {
    { chapter = 1, max_verse = 20 },
    { chapter = 2, max_verse = 15 },
    { chapter = 3, max_verse = 16 },
    { chapter = 4, max_verse = 16 },
    { chapter = 5, max_verse = 25 },
    { chapter = 6, max_verse = 21 },
  },
  ["2chronicles"] = {
    { chapter = 1,  max_verse = 17 },
    { chapter = 2,  max_verse = 18 },
    { chapter = 3,  max_verse = 17 },
    { chapter = 4,  max_verse = 22 },
    { chapter = 5,  max_verse = 14 },
    { chapter = 6,  max_verse = 42 },
    { chapter = 7,  max_verse = 22 },
    { chapter = 8,  max_verse = 18 },
    { chapter = 9,  max_verse = 31 },
    { chapter = 10, max_verse = 19 },
    { chapter = 11, max_verse = 23 },
    { chapter = 12, max_verse = 16 },
    { chapter = 13, max_verse = 22 },
    { chapter = 14, max_verse = 15 },
    { chapter = 15, max_verse = 19 },
    { chapter = 16, max_verse = 14 },
    { chapter = 17, max_verse = 19 },
    { chapter = 18, max_verse = 34 },
    { chapter = 19, max_verse = 11 },
    { chapter = 20, max_verse = 37 },
    { chapter = 21, max_verse = 20 },
    { chapter = 22, max_verse = 12 },
    { chapter = 23, max_verse = 21 },
    { chapter = 24, max_verse = 27 },
    { chapter = 25, max_verse = 28 },
    { chapter = 26, max_verse = 23 },
    { chapter = 27, max_verse = 9 },
    { chapter = 28, max_verse = 27 },
    { chapter = 29, max_verse = 36 },
    { chapter = 30, max_verse = 27 },
    { chapter = 31, max_verse = 21 },
    { chapter = 32, max_verse = 33 },
    { chapter = 33, max_verse = 25 },
    { chapter = 34, max_verse = 33 },
    { chapter = 35, max_verse = 27 },
    { chapter = 36, max_verse = 23 },
  },
  ["2corinthians"] = {
    { chapter = 1,  max_verse = 24 },
    { chapter = 2,  max_verse = 17 },
    { chapter = 3,  max_verse = 18 },
    { chapter = 4,  max_verse = 18 },
    { chapter = 5,  max_verse = 21 },
    { chapter = 6,  max_verse = 18 },
    { chapter = 7,  max_verse = 16 },
    { chapter = 8,  max_verse = 24 },
    { chapter = 9,  max_verse = 15 },
    { chapter = 10, max_verse = 18 },
    { chapter = 11, max_verse = 33 },
    { chapter = 12, max_verse = 21 },
    { chapter = 13, max_verse = 14 },
  },
  ["2john"] = { { chapter = 1, max_verse = 13 } },
  ["2kings"] = {
    { chapter = 1,  max_verse = 18 },
    { chapter = 2,  max_verse = 25 },
    { chapter = 3,  max_verse = 27 },
    { chapter = 4,  max_verse = 44 },
    { chapter = 5,  max_verse = 27 },
    { chapter = 6,  max_verse = 33 },
    { chapter = 7,  max_verse = 20 },
    { chapter = 8,  max_verse = 29 },
    { chapter = 9,  max_verse = 37 },
    { chapter = 10, max_verse = 36 },
    { chapter = 11, max_verse = 21 },
    { chapter = 12, max_verse = 21 },
    { chapter = 13, max_verse = 25 },
    { chapter = 14, max_verse = 29 },
    { chapter = 15, max_verse = 38 },
    { chapter = 16, max_verse = 20 },
    { chapter = 17, max_verse = 41 },
    { chapter = 18, max_verse = 37 },
    { chapter = 19, max_verse = 37 },
    { chapter = 20, max_verse = 21 },
    { chapter = 21, max_verse = 26 },
    { chapter = 22, max_verse = 20 },
    { chapter = 23, max_verse = 37 },
    { chapter = 24, max_verse = 20 },
    { chapter = 25, max_verse = 30 },
  },
  ["2peter"] = {
    { chapter = 1, max_verse = 21 },
    { chapter = 2, max_verse = 22 },
    { chapter = 3, max_verse = 18 },
  },
  ["2samuel"] = {
    { chapter = 1,  max_verse = 27 },
    { chapter = 2,  max_verse = 32 },
    { chapter = 3,  max_verse = 39 },
    { chapter = 4,  max_verse = 12 },
    { chapter = 5,  max_verse = 25 },
    { chapter = 6,  max_verse = 23 },
    { chapter = 7,  max_verse = 29 },
    { chapter = 8,  max_verse = 18 },
    { chapter = 9,  max_verse = 13 },
    { chapter = 10, max_verse = 19 },
    { chapter = 11, max_verse = 27 },
    { chapter = 12, max_verse = 31 },
    { chapter = 13, max_verse = 39 },
    { chapter = 14, max_verse = 33 },
    { chapter = 15, max_verse = 37 },
    { chapter = 16, max_verse = 23 },
    { chapter = 17, max_verse = 29 },
    { chapter = 18, max_verse = 33 },
    { chapter = 19, max_verse = 43 },
    { chapter = 20, max_verse = 26 },
    { chapter = 21, max_verse = 22 },
    { chapter = 22, max_verse = 51 },
    { chapter = 23, max_verse = 39 },
    { chapter = 24, max_verse = 25 },
  },
  ["2thessalonians"] = {
    { chapter = 1, max_verse = 12 },
    { chapter = 2, max_verse = 17 },
    { chapter = 3, max_verse = 18 },
  },
  ["2timothy"] = {
    { chapter = 1, max_verse = 18 },
    { chapter = 2, max_verse = 26 },
    { chapter = 3, max_verse = 17 },
    { chapter = 4, max_verse = 22 },
  },
  ["3john"] = { { chapter = 1, max_verse = 14 } },
  acts = {
    { chapter = 1,  max_verse = 26 },
    { chapter = 2,  max_verse = 47 },
    { chapter = 3,  max_verse = 26 },
    { chapter = 4,  max_verse = 37 },
    { chapter = 5,  max_verse = 42 },
    { chapter = 6,  max_verse = 15 },
    { chapter = 7,  max_verse = 60 },
    { chapter = 8,  max_verse = 40 },
    { chapter = 9,  max_verse = 43 },
    { chapter = 10, max_verse = 48 },
    { chapter = 11, max_verse = 30 },
    { chapter = 12, max_verse = 25 },
    { chapter = 13, max_verse = 52 },
    { chapter = 14, max_verse = 28 },
    { chapter = 15, max_verse = 41 },
    { chapter = 16, max_verse = 40 },
    { chapter = 17, max_verse = 34 },
    { chapter = 18, max_verse = 28 },
    { chapter = 19, max_verse = 41 },
    { chapter = 20, max_verse = 38 },
    { chapter = 21, max_verse = 40 },
    { chapter = 22, max_verse = 30 },
    { chapter = 23, max_verse = 35 },
    { chapter = 24, max_verse = 27 },
    { chapter = 25, max_verse = 27 },
    { chapter = 26, max_verse = 32 },
    { chapter = 27, max_verse = 44 },
    { chapter = 28, max_verse = 31 },
  },
  amos = {
    { chapter = 1, max_verse = 15 },
    { chapter = 2, max_verse = 16 },
    { chapter = 3, max_verse = 15 },
    { chapter = 4, max_verse = 13 },
    { chapter = 5, max_verse = 27 },
    { chapter = 6, max_verse = 14 },
    { chapter = 7, max_verse = 17 },
    { chapter = 8, max_verse = 14 },
    { chapter = 9, max_verse = 15 },
  },
  colossians = {
    { chapter = 1, max_verse = 29 },
    { chapter = 2, max_verse = 23 },
    { chapter = 3, max_verse = 25 },
    { chapter = 4, max_verse = 18 },
  },
  daniel = {
    { chapter = 1,  max_verse = 21 },
    { chapter = 2,  max_verse = 49 },
    { chapter = 3,  max_verse = 30 },
    { chapter = 4,  max_verse = 37 },
    { chapter = 5,  max_verse = 31 },
    { chapter = 6,  max_verse = 28 },
    { chapter = 7,  max_verse = 28 },
    { chapter = 8,  max_verse = 27 },
    { chapter = 9,  max_verse = 27 },
    { chapter = 10, max_verse = 21 },
    { chapter = 11, max_verse = 45 },
    { chapter = 12, max_verse = 13 },
  },
  deuteronomy = {
    { chapter = 1,  max_verse = 46 },
    { chapter = 2,  max_verse = 37 },
    { chapter = 3,  max_verse = 29 },
    { chapter = 4,  max_verse = 49 },
    { chapter = 5,  max_verse = 33 },
    { chapter = 6,  max_verse = 25 },
    { chapter = 7,  max_verse = 26 },
    { chapter = 8,  max_verse = 20 },
    { chapter = 9,  max_verse = 29 },
    { chapter = 10, max_verse = 22 },
    { chapter = 11, max_verse = 32 },
    { chapter = 12, max_verse = 32 },
    { chapter = 13, max_verse = 18 },
    { chapter = 14, max_verse = 29 },
    { chapter = 15, max_verse = 23 },
    { chapter = 16, max_verse = 22 },
    { chapter = 17, max_verse = 20 },
    { chapter = 18, max_verse = 22 },
    { chapter = 19, max_verse = 21 },
    { chapter = 20, max_verse = 20 },
    { chapter = 21, max_verse = 23 },
    { chapter = 22, max_verse = 30 },
    { chapter = 23, max_verse = 25 },
    { chapter = 24, max_verse = 22 },
    { chapter = 25, max_verse = 19 },
    { chapter = 26, max_verse = 19 },
    { chapter = 27, max_verse = 26 },
    { chapter = 28, max_verse = 68 },
    { chapter = 29, max_verse = 29 },
    { chapter = 30, max_verse = 20 },
    { chapter = 31, max_verse = 30 },
    { chapter = 32, max_verse = 52 },
    { chapter = 33, max_verse = 29 },
    { chapter = 34, max_verse = 12 },
  },
  ecclesiastes = {
    { chapter = 1,  max_verse = 18 },
    { chapter = 2,  max_verse = 26 },
    { chapter = 3,  max_verse = 22 },
    { chapter = 4,  max_verse = 16 },
    { chapter = 5,  max_verse = 20 },
    { chapter = 6,  max_verse = 12 },
    { chapter = 7,  max_verse = 29 },
    { chapter = 8,  max_verse = 17 },
    { chapter = 9,  max_verse = 18 },
    { chapter = 10, max_verse = 20 },
    { chapter = 11, max_verse = 10 },
    { chapter = 12, max_verse = 14 },
  },
  ephesians = {
    { chapter = 1, max_verse = 23 },
    { chapter = 2, max_verse = 22 },
    { chapter = 3, max_verse = 21 },
    { chapter = 4, max_verse = 32 },
    { chapter = 5, max_verse = 33 },
    { chapter = 6, max_verse = 24 },
  },
  esther = {
    { chapter = 1,  max_verse = 22 },
    { chapter = 2,  max_verse = 23 },
    { chapter = 3,  max_verse = 15 },
    { chapter = 4,  max_verse = 17 },
    { chapter = 5,  max_verse = 14 },
    { chapter = 6,  max_verse = 14 },
    { chapter = 7,  max_verse = 10 },
    { chapter = 8,  max_verse = 17 },
    { chapter = 9,  max_verse = 32 },
    { chapter = 10, max_verse = 3 },
  },
  exodus = {
    { chapter = 1,  max_verse = 22 },
    { chapter = 2,  max_verse = 25 },
    { chapter = 3,  max_verse = 22 },
    { chapter = 4,  max_verse = 31 },
    { chapter = 5,  max_verse = 23 },
    { chapter = 6,  max_verse = 30 },
    { chapter = 7,  max_verse = 25 },
    { chapter = 8,  max_verse = 32 },
    { chapter = 9,  max_verse = 35 },
    { chapter = 10, max_verse = 29 },
    { chapter = 11, max_verse = 10 },
    { chapter = 12, max_verse = 51 },
    { chapter = 13, max_verse = 22 },
    { chapter = 14, max_verse = 31 },
    { chapter = 15, max_verse = 27 },
    { chapter = 16, max_verse = 36 },
    { chapter = 17, max_verse = 16 },
    { chapter = 18, max_verse = 27 },
    { chapter = 19, max_verse = 25 },
    { chapter = 20, max_verse = 26 },
    { chapter = 21, max_verse = 36 },
    { chapter = 22, max_verse = 31 },
    { chapter = 23, max_verse = 33 },
    { chapter = 24, max_verse = 18 },
    { chapter = 25, max_verse = 40 },
    { chapter = 26, max_verse = 37 },
    { chapter = 27, max_verse = 21 },
    { chapter = 28, max_verse = 43 },
    { chapter = 29, max_verse = 46 },
    { chapter = 30, max_verse = 38 },
    { chapter = 31, max_verse = 18 },
    { chapter = 32, max_verse = 35 },
    { chapter = 33, max_verse = 23 },
    { chapter = 34, max_verse = 35 },
    { chapter = 35, max_verse = 35 },
    { chapter = 36, max_verse = 38 },
    { chapter = 37, max_verse = 29 },
    { chapter = 38, max_verse = 31 },
    { chapter = 39, max_verse = 43 },
    { chapter = 40, max_verse = 38 },
  },
  ezekiel = {
    { chapter = 1,  max_verse = 28 },
    { chapter = 2,  max_verse = 10 },
    { chapter = 3,  max_verse = 27 },
    { chapter = 4,  max_verse = 17 },
    { chapter = 5,  max_verse = 17 },
    { chapter = 6,  max_verse = 14 },
    { chapter = 7,  max_verse = 27 },
    { chapter = 8,  max_verse = 18 },
    { chapter = 9,  max_verse = 11 },
    { chapter = 10, max_verse = 22 },
    { chapter = 11, max_verse = 25 },
    { chapter = 12, max_verse = 28 },
    { chapter = 13, max_verse = 23 },
    { chapter = 14, max_verse = 23 },
    { chapter = 15, max_verse = 8 },
    { chapter = 16, max_verse = 63 },
    { chapter = 17, max_verse = 24 },
    { chapter = 18, max_verse = 32 },
    { chapter = 19, max_verse = 14 },
    { chapter = 20, max_verse = 49 },
    { chapter = 21, max_verse = 32 },
    { chapter = 22, max_verse = 31 },
    { chapter = 23, max_verse = 49 },
    { chapter = 24, max_verse = 27 },
    { chapter = 25, max_verse = 17 },
    { chapter = 26, max_verse = 21 },
    { chapter = 27, max_verse = 36 },
    { chapter = 28, max_verse = 26 },
    { chapter = 29, max_verse = 21 },
    { chapter = 30, max_verse = 26 },
    { chapter = 31, max_verse = 18 },
    { chapter = 32, max_verse = 32 },
    { chapter = 33, max_verse = 33 },
    { chapter = 34, max_verse = 31 },
    { chapter = 35, max_verse = 15 },
    { chapter = 36, max_verse = 38 },
    { chapter = 37, max_verse = 28 },
    { chapter = 38, max_verse = 23 },
    { chapter = 39, max_verse = 29 },
    { chapter = 40, max_verse = 49 },
    { chapter = 41, max_verse = 26 },
    { chapter = 42, max_verse = 20 },
    { chapter = 43, max_verse = 27 },
    { chapter = 44, max_verse = 31 },
    { chapter = 45, max_verse = 25 },
    { chapter = 46, max_verse = 24 },
    { chapter = 47, max_verse = 23 },
    { chapter = 48, max_verse = 35 },
  },
  ezra = {
    { chapter = 1,  max_verse = 11 },
    { chapter = 2,  max_verse = 70 },
    { chapter = 3,  max_verse = 13 },
    { chapter = 4,  max_verse = 24 },
    { chapter = 5,  max_verse = 17 },
    { chapter = 6,  max_verse = 22 },
    { chapter = 7,  max_verse = 28 },
    { chapter = 8,  max_verse = 36 },
    { chapter = 9,  max_verse = 15 },
    { chapter = 10, max_verse = 44 },
  },
  galatians = {
    { chapter = 1, max_verse = 24 },
    { chapter = 2, max_verse = 21 },
    { chapter = 3, max_verse = 29 },
    { chapter = 4, max_verse = 31 },
    { chapter = 5, max_verse = 26 },
    { chapter = 6, max_verse = 18 },
  },
  genesis = {
    { chapter = 1,  max_verse = 31 },
    { chapter = 2,  max_verse = 25 },
    { chapter = 3,  max_verse = 24 },
    { chapter = 4,  max_verse = 26 },
    { chapter = 5,  max_verse = 32 },
    { chapter = 6,  max_verse = 22 },
    { chapter = 7,  max_verse = 24 },
    { chapter = 8,  max_verse = 22 },
    { chapter = 9,  max_verse = 29 },
    { chapter = 10, max_verse = 32 },
    { chapter = 11, max_verse = 32 },
    { chapter = 12, max_verse = 20 },
    { chapter = 13, max_verse = 18 },
    { chapter = 14, max_verse = 24 },
    { chapter = 15, max_verse = 21 },
    { chapter = 16, max_verse = 16 },
    { chapter = 17, max_verse = 27 },
    { chapter = 18, max_verse = 33 },
    { chapter = 19, max_verse = 38 },
    { chapter = 20, max_verse = 18 },
    { chapter = 21, max_verse = 34 },
    { chapter = 22, max_verse = 24 },
    { chapter = 23, max_verse = 20 },
    { chapter = 24, max_verse = 67 },
    { chapter = 25, max_verse = 34 },
    { chapter = 26, max_verse = 35 },
    { chapter = 27, max_verse = 46 },
    { chapter = 28, max_verse = 22 },
    { chapter = 29, max_verse = 35 },
    { chapter = 30, max_verse = 43 },
    { chapter = 31, max_verse = 55 },
    { chapter = 32, max_verse = 32 },
    { chapter = 33, max_verse = 20 },
    { chapter = 34, max_verse = 31 },
    { chapter = 35, max_verse = 29 },
    { chapter = 36, max_verse = 43 },
    { chapter = 37, max_verse = 36 },
    { chapter = 38, max_verse = 30 },
    { chapter = 39, max_verse = 23 },
    { chapter = 40, max_verse = 23 },
    { chapter = 41, max_verse = 57 },
    { chapter = 42, max_verse = 38 },
    { chapter = 43, max_verse = 34 },
    { chapter = 44, max_verse = 34 },
    { chapter = 45, max_verse = 28 },
    { chapter = 46, max_verse = 34 },
    { chapter = 47, max_verse = 31 },
    { chapter = 48, max_verse = 22 },
    { chapter = 49, max_verse = 33 },
    { chapter = 50, max_verse = 26 },
  },
  habakkuk = {
    { chapter = 1, max_verse = 17 },
    { chapter = 2, max_verse = 20 },
    { chapter = 3, max_verse = 19 },
  },
  haggai = { { chapter = 1, max_verse = 15 }, { chapter = 2, max_verse = 23 } },
  hebrews = {
    { chapter = 1,  max_verse = 14 },
    { chapter = 2,  max_verse = 18 },
    { chapter = 3,  max_verse = 19 },
    { chapter = 4,  max_verse = 16 },
    { chapter = 5,  max_verse = 14 },
    { chapter = 6,  max_verse = 20 },
    { chapter = 7,  max_verse = 28 },
    { chapter = 8,  max_verse = 13 },
    { chapter = 9,  max_verse = 28 },
    { chapter = 10, max_verse = 39 },
    { chapter = 11, max_verse = 40 },
    { chapter = 12, max_verse = 29 },
    { chapter = 13, max_verse = 25 },
  },
  hosea = {
    { chapter = 1,  max_verse = 11 },
    { chapter = 2,  max_verse = 23 },
    { chapter = 3,  max_verse = 5 },
    { chapter = 4,  max_verse = 19 },
    { chapter = 5,  max_verse = 15 },
    { chapter = 6,  max_verse = 11 },
    { chapter = 7,  max_verse = 16 },
    { chapter = 8,  max_verse = 14 },
    { chapter = 9,  max_verse = 17 },
    { chapter = 10, max_verse = 15 },
    { chapter = 11, max_verse = 12 },
    { chapter = 12, max_verse = 14 },
    { chapter = 13, max_verse = 16 },
    { chapter = 14, max_verse = 9 },
  },
  isaiah = {
    { chapter = 1,  max_verse = 31 },
    { chapter = 2,  max_verse = 22 },
    { chapter = 3,  max_verse = 26 },
    { chapter = 4,  max_verse = 6 },
    { chapter = 5,  max_verse = 30 },
    { chapter = 6,  max_verse = 13 },
    { chapter = 7,  max_verse = 25 },
    { chapter = 8,  max_verse = 22 },
    { chapter = 9,  max_verse = 21 },
    { chapter = 10, max_verse = 34 },
    { chapter = 11, max_verse = 16 },
    { chapter = 12, max_verse = 6 },
    { chapter = 13, max_verse = 22 },
    { chapter = 14, max_verse = 32 },
    { chapter = 15, max_verse = 9 },
    { chapter = 16, max_verse = 14 },
    { chapter = 17, max_verse = 14 },
    { chapter = 18, max_verse = 7 },
    { chapter = 19, max_verse = 25 },
    { chapter = 20, max_verse = 6 },
    { chapter = 21, max_verse = 17 },
    { chapter = 22, max_verse = 25 },
    { chapter = 23, max_verse = 18 },
    { chapter = 24, max_verse = 23 },
    { chapter = 25, max_verse = 12 },
    { chapter = 26, max_verse = 21 },
    { chapter = 27, max_verse = 13 },
    { chapter = 28, max_verse = 29 },
    { chapter = 29, max_verse = 24 },
    { chapter = 30, max_verse = 33 },
    { chapter = 31, max_verse = 9 },
    { chapter = 32, max_verse = 20 },
    { chapter = 33, max_verse = 24 },
    { chapter = 34, max_verse = 17 },
    { chapter = 35, max_verse = 10 },
    { chapter = 36, max_verse = 22 },
    { chapter = 37, max_verse = 38 },
    { chapter = 38, max_verse = 22 },
    { chapter = 39, max_verse = 8 },
    { chapter = 40, max_verse = 31 },
    { chapter = 41, max_verse = 29 },
    { chapter = 42, max_verse = 25 },
    { chapter = 43, max_verse = 28 },
    { chapter = 44, max_verse = 28 },
    { chapter = 45, max_verse = 25 },
    { chapter = 46, max_verse = 13 },
    { chapter = 47, max_verse = 15 },
    { chapter = 48, max_verse = 22 },
    { chapter = 49, max_verse = 26 },
    { chapter = 50, max_verse = 11 },
    { chapter = 51, max_verse = 23 },
    { chapter = 52, max_verse = 15 },
    { chapter = 53, max_verse = 12 },
    { chapter = 54, max_verse = 17 },
    { chapter = 55, max_verse = 13 },
    { chapter = 56, max_verse = 12 },
    { chapter = 57, max_verse = 21 },
    { chapter = 58, max_verse = 14 },
    { chapter = 59, max_verse = 21 },
    { chapter = 60, max_verse = 22 },
    { chapter = 61, max_verse = 11 },
    { chapter = 62, max_verse = 12 },
    { chapter = 63, max_verse = 19 },
    { chapter = 64, max_verse = 12 },
    { chapter = 65, max_verse = 25 },
    { chapter = 66, max_verse = 24 },
  },
  james = {
    { chapter = 1, max_verse = 27 },
    { chapter = 2, max_verse = 26 },
    { chapter = 3, max_verse = 18 },
    { chapter = 4, max_verse = 17 },
    { chapter = 5, max_verse = 20 },
  },
  jeremiah = {
    { chapter = 1,  max_verse = 19 },
    { chapter = 2,  max_verse = 37 },
    { chapter = 3,  max_verse = 25 },
    { chapter = 4,  max_verse = 31 },
    { chapter = 5,  max_verse = 31 },
    { chapter = 6,  max_verse = 30 },
    { chapter = 7,  max_verse = 34 },
    { chapter = 8,  max_verse = 22 },
    { chapter = 9,  max_verse = 26 },
    { chapter = 10, max_verse = 25 },
    { chapter = 11, max_verse = 23 },
    { chapter = 12, max_verse = 17 },
    { chapter = 13, max_verse = 27 },
    { chapter = 14, max_verse = 22 },
    { chapter = 15, max_verse = 21 },
    { chapter = 16, max_verse = 21 },
    { chapter = 17, max_verse = 27 },
    { chapter = 18, max_verse = 23 },
    { chapter = 19, max_verse = 15 },
    { chapter = 20, max_verse = 18 },
    { chapter = 21, max_verse = 14 },
    { chapter = 22, max_verse = 30 },
    { chapter = 23, max_verse = 40 },
    { chapter = 24, max_verse = 10 },
    { chapter = 25, max_verse = 38 },
    { chapter = 26, max_verse = 24 },
    { chapter = 27, max_verse = 22 },
    { chapter = 28, max_verse = 17 },
    { chapter = 29, max_verse = 32 },
    { chapter = 30, max_verse = 24 },
    { chapter = 31, max_verse = 40 },
    { chapter = 32, max_verse = 44 },
    { chapter = 33, max_verse = 26 },
    { chapter = 34, max_verse = 22 },
    { chapter = 35, max_verse = 19 },
    { chapter = 36, max_verse = 32 },
    { chapter = 37, max_verse = 21 },
    { chapter = 38, max_verse = 28 },
    { chapter = 39, max_verse = 18 },
    { chapter = 40, max_verse = 16 },
    { chapter = 41, max_verse = 18 },
    { chapter = 42, max_verse = 22 },
    { chapter = 43, max_verse = 13 },
    { chapter = 44, max_verse = 30 },
    { chapter = 45, max_verse = 5 },
    { chapter = 46, max_verse = 28 },
    { chapter = 47, max_verse = 7 },
    { chapter = 48, max_verse = 47 },
    { chapter = 49, max_verse = 39 },
    { chapter = 50, max_verse = 46 },
    { chapter = 51, max_verse = 64 },
    { chapter = 52, max_verse = 34 },
  },
  job = {
    { chapter = 1,  max_verse = 22 },
    { chapter = 2,  max_verse = 13 },
    { chapter = 3,  max_verse = 26 },
    { chapter = 4,  max_verse = 21 },
    { chapter = 5,  max_verse = 27 },
    { chapter = 6,  max_verse = 30 },
    { chapter = 7,  max_verse = 21 },
    { chapter = 8,  max_verse = 22 },
    { chapter = 9,  max_verse = 35 },
    { chapter = 10, max_verse = 22 },
    { chapter = 11, max_verse = 20 },
    { chapter = 12, max_verse = 25 },
    { chapter = 13, max_verse = 28 },
    { chapter = 14, max_verse = 22 },
    { chapter = 15, max_verse = 35 },
    { chapter = 16, max_verse = 22 },
    { chapter = 17, max_verse = 16 },
    { chapter = 18, max_verse = 21 },
    { chapter = 19, max_verse = 29 },
    { chapter = 20, max_verse = 29 },
    { chapter = 21, max_verse = 34 },
    { chapter = 22, max_verse = 30 },
    { chapter = 23, max_verse = 17 },
    { chapter = 24, max_verse = 25 },
    { chapter = 25, max_verse = 6 },
    { chapter = 26, max_verse = 14 },
    { chapter = 27, max_verse = 23 },
    { chapter = 28, max_verse = 28 },
    { chapter = 29, max_verse = 25 },
    { chapter = 30, max_verse = 31 },
    { chapter = 31, max_verse = 40 },
    { chapter = 32, max_verse = 22 },
    { chapter = 33, max_verse = 33 },
    { chapter = 34, max_verse = 37 },
    { chapter = 35, max_verse = 16 },
    { chapter = 36, max_verse = 33 },
    { chapter = 37, max_verse = 24 },
    { chapter = 38, max_verse = 41 },
    { chapter = 39, max_verse = 30 },
    { chapter = 40, max_verse = 24 },
    { chapter = 41, max_verse = 34 },
    { chapter = 42, max_verse = 17 },
  },
  joel = {
    { chapter = 1, max_verse = 20 },
    { chapter = 2, max_verse = 32 },
    { chapter = 3, max_verse = 21 },
  },
  john = {
    { chapter = 1,  max_verse = 51 },
    { chapter = 2,  max_verse = 25 },
    { chapter = 3,  max_verse = 36 },
    { chapter = 4,  max_verse = 54 },
    { chapter = 5,  max_verse = 47 },
    { chapter = 6,  max_verse = 71 },
    { chapter = 7,  max_verse = 53 },
    { chapter = 8,  max_verse = 59 },
    { chapter = 9,  max_verse = 41 },
    { chapter = 10, max_verse = 42 },
    { chapter = 11, max_verse = 57 },
    { chapter = 12, max_verse = 50 },
    { chapter = 13, max_verse = 38 },
    { chapter = 14, max_verse = 31 },
    { chapter = 15, max_verse = 27 },
    { chapter = 16, max_verse = 33 },
    { chapter = 17, max_verse = 26 },
    { chapter = 18, max_verse = 40 },
    { chapter = 19, max_verse = 42 },
    { chapter = 20, max_verse = 31 },
    { chapter = 21, max_verse = 25 },
  },
  jonah = {
    { chapter = 1, max_verse = 17 },
    { chapter = 2, max_verse = 10 },
    { chapter = 3, max_verse = 10 },
    { chapter = 4, max_verse = 11 },
  },
  joshua = {
    { chapter = 1,  max_verse = 18 },
    { chapter = 2,  max_verse = 24 },
    { chapter = 3,  max_verse = 17 },
    { chapter = 4,  max_verse = 24 },
    { chapter = 5,  max_verse = 15 },
    { chapter = 6,  max_verse = 27 },
    { chapter = 7,  max_verse = 26 },
    { chapter = 8,  max_verse = 35 },
    { chapter = 9,  max_verse = 27 },
    { chapter = 10, max_verse = 43 },
    { chapter = 11, max_verse = 23 },
    { chapter = 12, max_verse = 24 },
    { chapter = 13, max_verse = 33 },
    { chapter = 14, max_verse = 15 },
    { chapter = 15, max_verse = 63 },
    { chapter = 16, max_verse = 10 },
    { chapter = 17, max_verse = 18 },
    { chapter = 18, max_verse = 28 },
    { chapter = 19, max_verse = 51 },
    { chapter = 20, max_verse = 9 },
    { chapter = 21, max_verse = 45 },
    { chapter = 22, max_verse = 34 },
    { chapter = 23, max_verse = 16 },
    { chapter = 24, max_verse = 33 },
  },
  jude = { { chapter = 1, max_verse = 25 } },
  judges = {
    { chapter = 1,  max_verse = 36 },
    { chapter = 2,  max_verse = 23 },
    { chapter = 3,  max_verse = 31 },
    { chapter = 4,  max_verse = 24 },
    { chapter = 5,  max_verse = 31 },
    { chapter = 6,  max_verse = 40 },
    { chapter = 7,  max_verse = 25 },
    { chapter = 8,  max_verse = 35 },
    { chapter = 9,  max_verse = 57 },
    { chapter = 10, max_verse = 18 },
    { chapter = 11, max_verse = 40 },
    { chapter = 12, max_verse = 15 },
    { chapter = 13, max_verse = 25 },
    { chapter = 14, max_verse = 20 },
    { chapter = 15, max_verse = 20 },
    { chapter = 16, max_verse = 31 },
    { chapter = 17, max_verse = 13 },
    { chapter = 18, max_verse = 31 },
    { chapter = 19, max_verse = 30 },
    { chapter = 20, max_verse = 48 },
    { chapter = 21, max_verse = 25 },
  },
  lamentations = {
    { chapter = 1, max_verse = 22 },
    { chapter = 2, max_verse = 22 },
    { chapter = 3, max_verse = 66 },
    { chapter = 4, max_verse = 22 },
    { chapter = 5, max_verse = 22 },
  },
  leviticus = {
    { chapter = 1,  max_verse = 17 },
    { chapter = 2,  max_verse = 16 },
    { chapter = 3,  max_verse = 17 },
    { chapter = 4,  max_verse = 35 },
    { chapter = 5,  max_verse = 19 },
    { chapter = 6,  max_verse = 30 },
    { chapter = 7,  max_verse = 38 },
    { chapter = 8,  max_verse = 36 },
    { chapter = 9,  max_verse = 24 },
    { chapter = 10, max_verse = 20 },
    { chapter = 11, max_verse = 47 },
    { chapter = 12, max_verse = 8 },
    { chapter = 13, max_verse = 59 },
    { chapter = 14, max_verse = 57 },
    { chapter = 15, max_verse = 33 },
    { chapter = 16, max_verse = 34 },
    { chapter = 17, max_verse = 16 },
    { chapter = 18, max_verse = 30 },
    { chapter = 19, max_verse = 37 },
    { chapter = 20, max_verse = 27 },
    { chapter = 21, max_verse = 24 },
    { chapter = 22, max_verse = 33 },
    { chapter = 23, max_verse = 44 },
    { chapter = 24, max_verse = 23 },
    { chapter = 25, max_verse = 55 },
    { chapter = 26, max_verse = 46 },
    { chapter = 27, max_verse = 34 },
  },
  luke = {
    { chapter = 1,  max_verse = 80 },
    { chapter = 2,  max_verse = 52 },
    { chapter = 3,  max_verse = 38 },
    { chapter = 4,  max_verse = 44 },
    { chapter = 5,  max_verse = 39 },
    { chapter = 6,  max_verse = 49 },
    { chapter = 7,  max_verse = 50 },
    { chapter = 8,  max_verse = 56 },
    { chapter = 9,  max_verse = 62 },
    { chapter = 10, max_verse = 42 },
    { chapter = 11, max_verse = 54 },
    { chapter = 12, max_verse = 59 },
    { chapter = 13, max_verse = 35 },
    { chapter = 14, max_verse = 35 },
    { chapter = 15, max_verse = 32 },
    { chapter = 16, max_verse = 31 },
    { chapter = 17, max_verse = 37 },
    { chapter = 18, max_verse = 43 },
    { chapter = 19, max_verse = 48 },
    { chapter = 20, max_verse = 47 },
    { chapter = 21, max_verse = 38 },
    { chapter = 22, max_verse = 71 },
    { chapter = 23, max_verse = 56 },
    { chapter = 24, max_verse = 53 },
  },
  malachi = {
    { chapter = 1, max_verse = 14 },
    { chapter = 2, max_verse = 17 },
    { chapter = 3, max_verse = 18 },
    { chapter = 4, max_verse = 6 },
  },
  mark = {
    { chapter = 1,  max_verse = 45 },
    { chapter = 2,  max_verse = 28 },
    { chapter = 3,  max_verse = 35 },
    { chapter = 4,  max_verse = 41 },
    { chapter = 5,  max_verse = 43 },
    { chapter = 6,  max_verse = 56 },
    { chapter = 7,  max_verse = 37 },
    { chapter = 8,  max_verse = 38 },
    { chapter = 9,  max_verse = 50 },
    { chapter = 10, max_verse = 52 },
    { chapter = 11, max_verse = 33 },
    { chapter = 12, max_verse = 44 },
    { chapter = 13, max_verse = 37 },
    { chapter = 14, max_verse = 72 },
    { chapter = 15, max_verse = 47 },
    { chapter = 16, max_verse = 20 },
  },
  matthew = {
    { chapter = 1,  max_verse = 25 },
    { chapter = 2,  max_verse = 23 },
    { chapter = 3,  max_verse = 17 },
    { chapter = 4,  max_verse = 25 },
    { chapter = 5,  max_verse = 48 },
    { chapter = 6,  max_verse = 34 },
    { chapter = 7,  max_verse = 29 },
    { chapter = 8,  max_verse = 34 },
    { chapter = 9,  max_verse = 38 },
    { chapter = 10, max_verse = 42 },
    { chapter = 11, max_verse = 30 },
    { chapter = 12, max_verse = 50 },
    { chapter = 13, max_verse = 58 },
    { chapter = 14, max_verse = 36 },
    { chapter = 15, max_verse = 39 },
    { chapter = 16, max_verse = 28 },
    { chapter = 17, max_verse = 27 },
    { chapter = 18, max_verse = 35 },
    { chapter = 19, max_verse = 30 },
    { chapter = 20, max_verse = 34 },
    { chapter = 21, max_verse = 46 },
    { chapter = 22, max_verse = 46 },
    { chapter = 23, max_verse = 39 },
    { chapter = 24, max_verse = 51 },
    { chapter = 25, max_verse = 46 },
    { chapter = 26, max_verse = 75 },
    { chapter = 27, max_verse = 66 },
    { chapter = 28, max_verse = 20 },
  },
  micah = {
    { chapter = 1, max_verse = 16 },
    { chapter = 2, max_verse = 13 },
    { chapter = 3, max_verse = 12 },
    { chapter = 4, max_verse = 13 },
    { chapter = 5, max_verse = 15 },
    { chapter = 6, max_verse = 16 },
    { chapter = 7, max_verse = 20 },
  },
  nahum = {
    { chapter = 1, max_verse = 15 },
    { chapter = 2, max_verse = 13 },
    { chapter = 3, max_verse = 19 },
  },
  nehemiah = {
    { chapter = 1,  max_verse = 11 },
    { chapter = 2,  max_verse = 20 },
    { chapter = 3,  max_verse = 32 },
    { chapter = 4,  max_verse = 23 },
    { chapter = 5,  max_verse = 19 },
    { chapter = 6,  max_verse = 19 },
    { chapter = 7,  max_verse = 73 },
    { chapter = 8,  max_verse = 18 },
    { chapter = 9,  max_verse = 38 },
    { chapter = 10, max_verse = 39 },
    { chapter = 11, max_verse = 36 },
    { chapter = 12, max_verse = 47 },
    { chapter = 13, max_verse = 31 },
  },
  numbers = {
    { chapter = 1,  max_verse = 54 },
    { chapter = 2,  max_verse = 34 },
    { chapter = 3,  max_verse = 51 },
    { chapter = 4,  max_verse = 49 },
    { chapter = 5,  max_verse = 31 },
    { chapter = 6,  max_verse = 27 },
    { chapter = 7,  max_verse = 89 },
    { chapter = 8,  max_verse = 26 },
    { chapter = 9,  max_verse = 23 },
    { chapter = 10, max_verse = 36 },
    { chapter = 11, max_verse = 35 },
    { chapter = 12, max_verse = 16 },
    { chapter = 13, max_verse = 33 },
    { chapter = 14, max_verse = 45 },
    { chapter = 15, max_verse = 41 },
    { chapter = 16, max_verse = 50 },
    { chapter = 17, max_verse = 13 },
    { chapter = 18, max_verse = 32 },
    { chapter = 19, max_verse = 22 },
    { chapter = 20, max_verse = 29 },
    { chapter = 21, max_verse = 35 },
    { chapter = 22, max_verse = 41 },
    { chapter = 23, max_verse = 30 },
    { chapter = 24, max_verse = 25 },
    { chapter = 25, max_verse = 18 },
    { chapter = 26, max_verse = 65 },
    { chapter = 27, max_verse = 23 },
    { chapter = 28, max_verse = 31 },
    { chapter = 29, max_verse = 40 },
    { chapter = 30, max_verse = 16 },
    { chapter = 31, max_verse = 54 },
    { chapter = 32, max_verse = 42 },
    { chapter = 33, max_verse = 56 },
    { chapter = 34, max_verse = 29 },
    { chapter = 35, max_verse = 34 },
    { chapter = 36, max_verse = 13 },
  },
  obadiah = { { chapter = 1, max_verse = 21 } },
  philemon = { { chapter = 1, max_verse = 25 } },
  philippians = {
    { chapter = 1, max_verse = 30 },
    { chapter = 2, max_verse = 30 },
    { chapter = 3, max_verse = 21 },
    { chapter = 4, max_verse = 23 },
  },
  proverbs = {
    { chapter = 1,  max_verse = 33 },
    { chapter = 2,  max_verse = 22 },
    { chapter = 3,  max_verse = 35 },
    { chapter = 4,  max_verse = 27 },
    { chapter = 5,  max_verse = 23 },
    { chapter = 6,  max_verse = 35 },
    { chapter = 7,  max_verse = 27 },
    { chapter = 8,  max_verse = 36 },
    { chapter = 9,  max_verse = 18 },
    { chapter = 10, max_verse = 32 },
    { chapter = 11, max_verse = 31 },
    { chapter = 12, max_verse = 28 },
    { chapter = 13, max_verse = 25 },
    { chapter = 14, max_verse = 35 },
    { chapter = 15, max_verse = 33 },
    { chapter = 16, max_verse = 33 },
    { chapter = 17, max_verse = 28 },
    { chapter = 18, max_verse = 24 },
    { chapter = 19, max_verse = 29 },
    { chapter = 20, max_verse = 30 },
    { chapter = 21, max_verse = 31 },
    { chapter = 22, max_verse = 29 },
    { chapter = 23, max_verse = 35 },
    { chapter = 24, max_verse = 34 },
    { chapter = 25, max_verse = 28 },
    { chapter = 26, max_verse = 28 },
    { chapter = 27, max_verse = 27 },
    { chapter = 28, max_verse = 28 },
    { chapter = 29, max_verse = 27 },
    { chapter = 30, max_verse = 33 },
    { chapter = 31, max_verse = 31 },
  },
  psalms = {
    { chapter = 1,   max_verse = 6 },
    { chapter = 2,   max_verse = 12 },
    { chapter = 3,   max_verse = 8 },
    { chapter = 4,   max_verse = 8 },
    { chapter = 5,   max_verse = 12 },
    { chapter = 6,   max_verse = 10 },
    { chapter = 7,   max_verse = 17 },
    { chapter = 8,   max_verse = 9 },
    { chapter = 9,   max_verse = 20 },
    { chapter = 10,  max_verse = 18 },
    { chapter = 11,  max_verse = 7 },
    { chapter = 12,  max_verse = 8 },
    { chapter = 13,  max_verse = 6 },
    { chapter = 14,  max_verse = 7 },
    { chapter = 15,  max_verse = 5 },
    { chapter = 16,  max_verse = 11 },
    { chapter = 17,  max_verse = 15 },
    { chapter = 18,  max_verse = 50 },
    { chapter = 19,  max_verse = 14 },
    { chapter = 20,  max_verse = 9 },
    { chapter = 21,  max_verse = 13 },
    { chapter = 22,  max_verse = 31 },
    { chapter = 23,  max_verse = 6 },
    { chapter = 24,  max_verse = 10 },
    { chapter = 25,  max_verse = 22 },
    { chapter = 26,  max_verse = 12 },
    { chapter = 27,  max_verse = 14 },
    { chapter = 28,  max_verse = 9 },
    { chapter = 29,  max_verse = 11 },
    { chapter = 30,  max_verse = 12 },
    { chapter = 31,  max_verse = 24 },
    { chapter = 32,  max_verse = 11 },
    { chapter = 33,  max_verse = 22 },
    { chapter = 34,  max_verse = 22 },
    { chapter = 35,  max_verse = 28 },
    { chapter = 36,  max_verse = 12 },
    { chapter = 37,  max_verse = 40 },
    { chapter = 38,  max_verse = 22 },
    { chapter = 39,  max_verse = 13 },
    { chapter = 40,  max_verse = 17 },
    { chapter = 41,  max_verse = 13 },
    { chapter = 42,  max_verse = 11 },
    { chapter = 43,  max_verse = 5 },
    { chapter = 44,  max_verse = 26 },
    { chapter = 45,  max_verse = 17 },
    { chapter = 46,  max_verse = 11 },
    { chapter = 47,  max_verse = 9 },
    { chapter = 48,  max_verse = 14 },
    { chapter = 49,  max_verse = 20 },
    { chapter = 50,  max_verse = 23 },
    { chapter = 51,  max_verse = 19 },
    { chapter = 52,  max_verse = 9 },
    { chapter = 53,  max_verse = 6 },
    { chapter = 54,  max_verse = 7 },
    { chapter = 55,  max_verse = 23 },
    { chapter = 56,  max_verse = 13 },
    { chapter = 57,  max_verse = 11 },
    { chapter = 58,  max_verse = 11 },
    { chapter = 59,  max_verse = 17 },
    { chapter = 60,  max_verse = 12 },
    { chapter = 61,  max_verse = 8 },
    { chapter = 62,  max_verse = 12 },
    { chapter = 63,  max_verse = 11 },
    { chapter = 64,  max_verse = 10 },
    { chapter = 65,  max_verse = 13 },
    { chapter = 66,  max_verse = 20 },
    { chapter = 67,  max_verse = 7 },
    { chapter = 68,  max_verse = 35 },
    { chapter = 69,  max_verse = 36 },
    { chapter = 70,  max_verse = 5 },
    { chapter = 71,  max_verse = 24 },
    { chapter = 72,  max_verse = 20 },
    { chapter = 73,  max_verse = 28 },
    { chapter = 74,  max_verse = 23 },
    { chapter = 75,  max_verse = 10 },
    { chapter = 76,  max_verse = 12 },
    { chapter = 77,  max_verse = 20 },
    { chapter = 78,  max_verse = 72 },
    { chapter = 79,  max_verse = 13 },
    { chapter = 80,  max_verse = 19 },
    { chapter = 81,  max_verse = 16 },
    { chapter = 82,  max_verse = 8 },
    { chapter = 83,  max_verse = 18 },
    { chapter = 84,  max_verse = 12 },
    { chapter = 85,  max_verse = 13 },
    { chapter = 86,  max_verse = 17 },
    { chapter = 87,  max_verse = 7 },
    { chapter = 88,  max_verse = 18 },
    { chapter = 89,  max_verse = 52 },
    { chapter = 90,  max_verse = 17 },
    { chapter = 91,  max_verse = 16 },
    { chapter = 92,  max_verse = 15 },
    { chapter = 93,  max_verse = 5 },
    { chapter = 94,  max_verse = 23 },
    { chapter = 95,  max_verse = 11 },
    { chapter = 96,  max_verse = 13 },
    { chapter = 97,  max_verse = 12 },
    { chapter = 98,  max_verse = 9 },
    { chapter = 99,  max_verse = 9 },
    { chapter = 100, max_verse = 5 },
    { chapter = 101, max_verse = 8 },
    { chapter = 102, max_verse = 28 },
    { chapter = 103, max_verse = 22 },
    { chapter = 104, max_verse = 35 },
    { chapter = 105, max_verse = 45 },
    { chapter = 106, max_verse = 48 },
    { chapter = 107, max_verse = 43 },
    { chapter = 108, max_verse = 13 },
    { chapter = 109, max_verse = 31 },
    { chapter = 110, max_verse = 7 },
    { chapter = 111, max_verse = 10 },
    { chapter = 112, max_verse = 10 },
    { chapter = 113, max_verse = 9 },
    { chapter = 114, max_verse = 8 },
    { chapter = 115, max_verse = 18 },
    { chapter = 116, max_verse = 19 },
    { chapter = 117, max_verse = 2 },
    { chapter = 118, max_verse = 29 },
    { chapter = 119, max_verse = 176 },
    { chapter = 120, max_verse = 7 },
    { chapter = 121, max_verse = 8 },
    { chapter = 122, max_verse = 9 },
    { chapter = 123, max_verse = 4 },
    { chapter = 124, max_verse = 8 },
    { chapter = 125, max_verse = 5 },
    { chapter = 126, max_verse = 6 },
    { chapter = 127, max_verse = 5 },
    { chapter = 128, max_verse = 6 },
    { chapter = 129, max_verse = 8 },
    { chapter = 130, max_verse = 8 },
    { chapter = 131, max_verse = 3 },
    { chapter = 132, max_verse = 18 },
    { chapter = 133, max_verse = 3 },
    { chapter = 134, max_verse = 3 },
    { chapter = 135, max_verse = 21 },
    { chapter = 136, max_verse = 26 },
    { chapter = 137, max_verse = 9 },
    { chapter = 138, max_verse = 8 },
    { chapter = 139, max_verse = 24 },
    { chapter = 140, max_verse = 13 },
    { chapter = 141, max_verse = 10 },
    { chapter = 142, max_verse = 7 },
    { chapter = 143, max_verse = 12 },
    { chapter = 144, max_verse = 15 },
    { chapter = 145, max_verse = 21 },
    { chapter = 146, max_verse = 10 },
    { chapter = 147, max_verse = 20 },
    { chapter = 148, max_verse = 14 },
    { chapter = 149, max_verse = 9 },
    { chapter = 150, max_verse = 6 },
  },
  revelation = {
    { chapter = 1,  max_verse = 20 },
    { chapter = 2,  max_verse = 29 },
    { chapter = 3,  max_verse = 22 },
    { chapter = 4,  max_verse = 11 },
    { chapter = 5,  max_verse = 14 },
    { chapter = 6,  max_verse = 17 },
    { chapter = 7,  max_verse = 17 },
    { chapter = 8,  max_verse = 13 },
    { chapter = 9,  max_verse = 21 },
    { chapter = 10, max_verse = 11 },
    { chapter = 11, max_verse = 19 },
    { chapter = 12, max_verse = 17 },
    { chapter = 13, max_verse = 18 },
    { chapter = 14, max_verse = 20 },
    { chapter = 15, max_verse = 8 },
    { chapter = 16, max_verse = 21 },
    { chapter = 17, max_verse = 18 },
    { chapter = 18, max_verse = 24 },
    { chapter = 19, max_verse = 21 },
    { chapter = 20, max_verse = 15 },
    { chapter = 21, max_verse = 27 },
    { chapter = 22, max_verse = 21 },
  },
  romans = {
    { chapter = 1,  max_verse = 32 },
    { chapter = 2,  max_verse = 29 },
    { chapter = 3,  max_verse = 31 },
    { chapter = 4,  max_verse = 25 },
    { chapter = 5,  max_verse = 21 },
    { chapter = 6,  max_verse = 23 },
    { chapter = 7,  max_verse = 25 },
    { chapter = 8,  max_verse = 39 },
    { chapter = 9,  max_verse = 33 },
    { chapter = 10, max_verse = 21 },
    { chapter = 11, max_verse = 36 },
    { chapter = 12, max_verse = 21 },
    { chapter = 13, max_verse = 14 },
    { chapter = 14, max_verse = 23 },
    { chapter = 15, max_verse = 33 },
    { chapter = 16, max_verse = 27 },
  },
  ruth = {
    { chapter = 1, max_verse = 22 },
    { chapter = 2, max_verse = 23 },
    { chapter = 3, max_verse = 18 },
    { chapter = 4, max_verse = 22 },
  },
  song = {
    { chapter = 1, max_verse = 17 },
    { chapter = 2, max_verse = 17 },
    { chapter = 3, max_verse = 11 },
    { chapter = 4, max_verse = 16 },
    { chapter = 5, max_verse = 16 },
    { chapter = 6, max_verse = 13 },
    { chapter = 7, max_verse = 13 },
    { chapter = 8, max_verse = 14 },
  },
  titus = {
    { chapter = 1, max_verse = 16 },
    { chapter = 2, max_verse = 15 },
    { chapter = 3, max_verse = 15 },
  },
  zechariah = {
    { chapter = 1,  max_verse = 21 },
    { chapter = 2,  max_verse = 13 },
    { chapter = 3,  max_verse = 10 },
    { chapter = 4,  max_verse = 14 },
    { chapter = 5,  max_verse = 11 },
    { chapter = 6,  max_verse = 15 },
    { chapter = 7,  max_verse = 14 },
    { chapter = 8,  max_verse = 23 },
    { chapter = 9,  max_verse = 17 },
    { chapter = 10, max_verse = 12 },
    { chapter = 11, max_verse = 17 },
    { chapter = 12, max_verse = 14 },
    { chapter = 13, max_verse = 9 },
    { chapter = 14, max_verse = 21 },
  },
  zephaniah = {
    { chapter = 1, max_verse = 18 },
    { chapter = 2, max_verse = 15 },
    { chapter = 3, max_verse = 20 },
  },
}

---@type string[]
local books = {
  "ezekiel",
  "ezra",
  "galatians",
  "genesis",
  "habakkuk",
  "haggai",
  "hebrews",
  "hosea",
  "isaiah",
  "james",
  "jeremiah",
  "joel",
  "john",
  "jonah",
  "joshua",
  "jude",
  "judges",
  "lamentations",
  "leviticus",
  "job",
  "malachi",
  "matthew",
  "micah",
  "nahum",
  "nehemiah",
  "obadiah",
  "philemon",
  "philippians",
  "proverbs",
  "1chronicles",
  "revelation",
  "romans",
  "ruth",
  "song",
  "titus",
  "zechariah",
  "numbers",
  "zephaniah",
  "psalms",
  "mark",
  "luke",
  "1corinthians",
  "1john",
  "1kings",
  "1peter",
  "1samuel",
  "1thessalonians",
  "1timothy",
  "2chronicles",
  "2corinthians",
  "2john",
  "2kings",
  "2peter",
  "2samuel",
  "2thessalonians",
  "2timothy",
  "3john",
  "acts",
  "amos",
  "colossians",
  "daniel",
  "deuteronomy",
  "ecclesiastes",
  "ephesians",
  "esther",
  "exodus",
}

function M.random_verse()
  local book_name = books[math.random(1, #books)]
  local book_chapter = math.random(1, #bible_data[book_name])
  local book_verse = math.random(1, bible_data[book_name][book_chapter].max_verse)
  return book_name .. " " .. book_chapter .. ":" .. book_verse
end

return M
