name: ci

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "bible-verse.nvim"
          version: "Neovim >= 0.9.0"
          demojify: true
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "doc: auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

