name: ci

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        neovim_version: ['nightly', 'v0.9.1', 'v0.9.2', 'v0.9.3', 'v0.9.4']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Setup diatheke
        run: |
          sudo apt install -y libsword-utils diatheke
          export SWORD_PATH="/tmp/bibleverse/.sword"
          mkdir -p "${SWORD_PATH}/mods.d"
          yes "yes" | installmgr -init
          yes "yes" | installmgr -sc
          yes "yes" | installmgr -r CrossWire
          yes "yes" | installmgr -ri CrossWire KJV

      - name: Run Tests
        run: |
          export SWORD_PATH="/tmp/bibleverse/.sword"
          command -v diatheke >/dev/null 2>&1 || exit 1
          nvim --version
          [ ! -d tests ] && exit 0
          nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"

  docs:
    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    needs: tests

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "bible-verse"
          version: "Neovim >= 0.9.1"
          demojify: true
          treesitter: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "doc: auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

